const inventoryTableData = [
    {
      id: "1",
      img: "/img/products/coffee.jpg",
      name: "Premium Coffee",
      sku: "COF-001",
      category: "Beverages",
      price: 4.99,
      cost: 2.50,
      stock: 42,
      threshold: 10,
      status: "in_stock",
      description: "High-quality arabica coffee beans, medium roast.",
      supplier: "Global Beans Inc.",
      barcode: "123456789012",
      customFields: { size: "12oz", roast: "Medium" },
    },
    {
      id: "2",
      img: "/img/products/tea.jpg",
      name: "Organic Tea",
      sku: "TEA-001",
      category: "Beverages",
      price: 3.99,
      cost: 1.75,
      stock: 8,
      threshold: 5,
      status: "low_stock",
      description: "Organic green tea leaves from Japan.",
      supplier: "Eastern Teas Ltd.",
      barcode: "987654321098",
      customFields: { size: "16oz", type: "Green" },
    },
    {
      id: "3",
      img: "/img/products/chocolate.jpg",
      name: "Dark Chocolate Bar",
      sku: "CHO-003",
      category: "Food",
      price: 2.50,
      cost: 1.10,
      stock: 20,
      threshold: 10,
      status: "in_stock",
      description: "85% dark chocolate bar made from organic cocoa.",
      supplier: "Sweet Treats Co.",
      barcode: "112233445566",
      customFields: { weight: "100g", cocoa: "85%" },
    },
    {
      id: "4",
      img: "/img/products/shampoo.jpg",
      name: "Herbal Shampoo",
      sku: "HBC-010",
      category: "Merchandise",
      price: 5.99,
      cost: 3.20,
      stock: 5,
      threshold: 6,
      status: "low_stock",
      description: "Natural herbal shampoo for all hair types.",
      supplier: "NatureCare Labs",
      barcode: "556677889900",
      customFields: { scent: "Lavender", volume: "250ml" },
    },
    {
      id: "5",
      img: "/img/products/water.jpg",
      name: "Mineral Water Bottle",
      sku: "WAT-101",
      category: "Beverages",
      price: 1.00,
      cost: 0.40,
      stock: 120,
      threshold: 20,
      status: "in_stock",
      description: "Pure mineral water in recyclable bottles.",
      supplier: "Blue Spring Ltd.",
      barcode: "334455667788",
      customFields: { size: "500ml", packaging: "Plastic Bottle" },
    },
    {
      id: "6",
      img: "/img/products/face-mask.jpg",
      name: "Reusable Face Mask",
      sku: "HYG-202",
      category: "Merchandise",
      price: 1.50,
      cost: 0.70,
      stock: 0,
      threshold: 5,
      status: "out_of_stock",
      description: "Washable and reusable cotton face masks.",
      supplier: "HealthGuard Inc.",
      barcode: "223344556677",
      customFields: { color: "Black", material: "Cotton" },
    },
    {
      id: "7",
      img: "/img/products/energy-drink.jpg",
      name: "Energy Drink",
      sku: "END-205",
      category: "Beverages",
      price: 2.99,
      cost: 1.25,
      stock: 35,
      threshold: 15,
      status: "in_stock",
      description: "Sugar-free energy drink with natural caffeine.",
      supplier: "Vitality Beverages",
      barcode: "445566778899",
      customFields: { flavor: "Berry", volume: "250ml" },
    },
    {
      id: "8",
      img: "/img/products/notebook.jpg",
      name: "Premium Notebook",
      sku: "STN-310",
      category: "Stationery",
      price: 6.50,
      cost: 3.00,
      stock: 18,
      threshold: 10,
      status: "in_stock",
      description: "Hardcover notebook with 120 pages.",
      supplier: "PaperWorks Co.",
      barcode: "556677889911",
      customFields: { color: "Blue", pages: "120" },
    },
    {
      id: "9",
      img: "/img/products/headphones.jpg",
      name: "Wireless Headphones",
      sku: "ELC-415",
      category: "Electronics",
      price: 59.99,
      cost: 32.00,
      stock: 7,
      threshold: 5,
      status: "low_stock",
      description: "Bluetooth headphones with noise cancellation.",
      supplier: "AudioTech Ltd.",
      barcode: "667788990011",
      customFields: { color: "Black", battery: "20hrs" },
    },
    {
      id: "10",
      img: "/img/products/backpack.jpg",
      name: "Travel Backpack",
      sku: "ACC-520",
      category: "Accessories",
      price: 29.99,
      cost: 15.50,
      stock: 3,
      threshold: 5,
      status: "low_stock",
      description: "Water-resistant backpack with USB charging port.",
      supplier: "Urban Gear",
      barcode: "778899001122",
      customFields: { capacity: "30L", color: "Gray" },
    },
    {
      id: "11",
      img: "/img/products/sunscreen.jpg",
      name: "SPF 50 Sunscreen",
      sku: "BEA-615",
      category: "Beauty",
      price: 12.99,
      cost: 6.80,
      stock: 22,
      threshold: 10,
      status: "in_stock",
      description: "Broad spectrum sunscreen for sensitive skin.",
      supplier: "SkinSafe Labs",
      barcode: "889900112233",
      customFields: { size: "100ml", spf: "50" },
    },
    {
      id: "12",
      img: "/img/products/protein-bar.jpg",
      name: "Protein Bar",
      sku: "NUT-720",
      category: "Food",
      price: 2.25,
      cost: 1.10,
      stock: 45,
      threshold: 20,
      status: "in_stock",
      description: "High-protein snack bar with natural ingredients.",
      supplier: "NutriFuel Inc.",
      barcode: "990011223344",
      customFields: { flavor: "Chocolate", protein: "20g" },
    },
    {
      id: "13",
      img: "/img/products/umbrella.jpg",
      name: "Compact Umbrella",
      sku: "ACC-825",
      category: "Accessories",
      price: 9.99,
      cost: 4.50,
      stock: 0,
      threshold: 5,
      status: "out_of_stock",
      description: "Windproof travel umbrella with automatic open.",
      supplier: "WeatherGear Co.",
      barcode: "001122334455",
      customFields: { color: "Black", diameter: "42in" },
    },
    {
      id: "14",
      img: "/img/products/yoga-mat.jpg",
      name: "Yoga Mat",
      sku: "FIT-930",
      category: "Fitness",
      price: 19.99,
      cost: 9.75,
      stock: 12,
      threshold: 8,
      status: "in_stock",
      description: "Non-slip yoga mat with carrying strap.",
      supplier: "ActiveLife Gear",
      barcode: "112233445566",
      customFields: { thickness: "5mm", color: "Purple" },
    },
    {
      id: "15",
      img: "/img/products/phone-case.jpg",
      name: "Smartphone Case",
      sku: "ELC-1040",
      category: "Electronics",
      price: 14.99,
      cost: 7.20,
      stock: 4,
      threshold: 5,
      status: "low_stock",
      description: "Shockproof case for latest smartphone models.",
      supplier: "TechArmor Inc.",
      barcode: "223344556677",
      customFields: { model: "iPhone 14", color: "Clear" },
    },
    {
      id: "16",
      img: "/img/products/candle.jpg",
      name: "Soy Candle",
      sku: "HOM-1150",
      category: "Home",
      price: 8.50,
      cost: 3.80,
      stock: 25,
      threshold: 10,
      status: "in_stock",
      description: "Natural soy wax candle with essential oils.",
      supplier: "CozyHome Goods",
      barcode: "334455667788",
      customFields: { scent: "Vanilla", burnTime: "40hrs" },
    },
    {
      id: "17",
      img: "/img/products/pens.jpg",
      name: "Gel Pen Set",
      sku: "STN-1260",
      category: "Stationery",
      price: 5.25,
      cost: 2.30,
      stock: 30,
      threshold: 15,
      status: "in_stock",
      description: "Set of 6 smooth-writing gel pens.",
      supplier: "WriteRight Co.",
      barcode: "445566778899",
      customFields: { colors: "6", tip: "0.7mm" },
    },
    {
      id: "18",
      img: "/img/products/socks.jpg",
      name: "Athletic Socks",
      sku: "CLO-1370",
      category: "Clothing",
      price: 7.99,
      cost: 3.50,
      stock: 2,
      threshold: 10,
      status: "low_stock",
      description: "Moisture-wicking performance socks.",
      supplier: "FootComfort Inc.",
      barcode: "556677889900",
      customFields: { size: "M", pairCount: "3" },
    },
    {
      id: "19",
      img: "/img/products/blender.jpg",
      name: "Personal Blender",
      sku: "KIT-1480",
      category: "Kitchen",
      price: 24.99,
      cost: 12.00,
      stock: 9,
      threshold: 5,
      status: "in_stock",
      description: "Single-serve blender with travel lid.",
      supplier: "KitchenEssentials",
      barcode: "667788990011",
      customFields: { color: "Red", power: "300W" },
    },
    {
      id: "20",
      img: "/img/products/plant.jpg",
      name: "Succulent Plant",
      sku: "HOM-1590",
      category: "Home",
      price: 6.99,
      cost: 2.80,
      stock: 15,
      threshold: 5,
      status: "in_stock",
      description: "Low-maintenance succulent in ceramic pot.",
      supplier: "GreenThumb Nursery",
      barcode: "778899001122",
      customFields: { type: "Echeveria", potSize: "3in" },
    }
  ];

  export default inventoryTableData;